<div class="wzlb">
      <div class="wzlb1"><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a>[field:pubdate function="GetDateTimeMK(@me)"/]</div>
      <div class="wzlb2">
        <div class="wzlb201">[field:description/]...<a href="[field:arcurl/]" title="[field:title/]" target="_blank">[详细]</a>
        </div>
        <div class="wzlb202"> 
            <a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:litpic/]" border="0" width="100" height="75"  /></a>
        </div>
      </div>
    </div>