
-----------------------------------------------
<m:top name='Ä£¿é¹ÜÀí' c='6,' display='block'>
    <m:item name='Ä£¿é¹ÜÀí' link='module_main.php' rank='sys_module' target='main' />
    <m:item name='ÉÏ´«ÐÂÄ£¿é' link='module_upload.php' rank='sys_module' target='main' />
    <m:item name='Ä£¿éÉú³ÉÏòµ¼' link='module_make.php' rank='sys_module' target='main' />
    </m:top>
<m:top item='7' name='¸¨Öú²å¼þ' display='block'>
  <m:item name='²å¼þ¹ÜÀíÆ÷' link='plus_main.php' rank='10' target='main' />
  <m:item name='æŒ‘é”™ç®¡ç†' link='erraddsave.php' rank='plus_æŒ‘é”™ç®¡ç†' target='main' />
<m:item name='ç™¾åº¦æ–°é—»' link='baidunews.php' rank='plus_ç™¾åº¦æ–°é—»' target='main' />
<m:item name='æ–‡ä»¶ç®¡ç†å™¨' link='file_manage_main.php' rank='plus_æ–‡ä»¶ç®¡ç†å™¨' target='main' />
<m:item name='å¹¿å‘Šç®¡ç†' link='ad_main.php' rank='plus_å¹¿å‘Šç®¡ç†' target='main' />
<m:item name='å‹æƒ…é“¾æŽ¥' link='friendlink_main.php' rank='plus_å‹æƒ…é“¾æŽ¥' target='main' />
<m:item name='æŠ•ç¥¨æ¨¡å—' link='vote_main.php' rank='plus_æŠ•ç¥¨æ¨¡å—' target='main' />

</m:top>

<m:top name='ç•…è¨€è¯„è®º' display='block'>
<m:item name='ç•…è¨€æ¨¡å—' link='changyan_main.php' rank='sys_Feedback' target='main'/>
<m:item name='è¯„è®ºç®¡ç†' link='changyan_main.php?dopost=manage' rank='sys_Feedback' target='main'/>
<m:item name='æ•°æ®ç»Ÿè®¡' link='changyan_main.php?dopost=stat' rank='sys_Feedback' target='main'/>
<m:item name='å¯¼å…¥å¯¼å‡º' link='changyan_main.php?dopost=import' rank='sys_Feedback' target='main'/>
<m:item name='ç•…è¨€è®¾ç½®' link='changyan_main.php?dopost=setting' rank='sys_Feedback' target='main'/>
</m:top>







-----------------------------------------------
