<dl class="list-none metlist">
              <dt class="title">
                <a href="{dede:global.cfg_cmsurl/}/plus/view.php?aid=[field:sortid/]"><span class="name">[field:attname/]</span></a>
               <!--  <span class="time">[field:att/]</span></dt> -->
             <!--  <dd class="info"><span class="tt">留言内容</span><span class="text">[field:content/]...</span></dd> -->
            </dl>