<article id="post-304" class="post-304 post type-post status-publish format-standard hentry category-changdao-jingdian">
				<header class="entry-header">
			
						<h1 class="entry-title">
				<a href="[field:arcurl/]" rel="bookmark">[field:title/]</a>
			</h1>
										<div class="comments-link">
					<a href="[field:arcurl/]#respond" title="[field:title/]"><span class="leave-reply">发表回复</span></a>				</div><!-- .comments-link -->
					</header><!-- .entry-header -->

				<div class="entry-content">
			<p>[field:description/]...</p>
<p><img alt="" src="[field:picname/]" /></p>
<p>[field:info function='cn_substr(@me,100)'/] <a href="[field:arcurl/]" class="more-link">继续阅读 <span class="meta-nav">&rarr;</span></a></p>
					</div><!-- .entry-content -->
		
		<footer class="entry-meta">
			本条目发布于<a href="[field:arcurl/]" title="上午10:19" rel="bookmark"><time class="entry-date" datetime="2014-04-12T10:19:44+00:00">[field:pubdate function="GetDateMK(@me)"/]</time></a>。属于<a href="[field:typeurl /]" rel="category tag">[field:typename /]</a>分类。<span class="by-author">作者是<span class="author vcard"><a class="url fn n" href="#" title="查看所有由[field:writer /]发布的文章" rel="author">[field:writer /]</a></span>。</span>								</footer><!-- .entry-meta -->
	</article><!-- #post -->