<?php
$z[0]=Array("global","",118,151);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",164,197);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",240,273);
$z[2][4]['name']="cfg_webbiao";
$z[3]=Array("global","",699,733);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("channel","\r\n     <li id=\"menu-item-60\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-60\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",773,1270);
$z[4][4]['type']="top";
$z[4][4]['row']="8";
$z[4][4]['currentstyle']="<li id='menu-item-40' class='menu-item menu-item-type-taxonomy menu-item-object-category current-post-ancestor current-menu-parent current-post-parent menu-item-40'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("global","",1347,1381);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",1469,1502);
$z[6][4]['name']="cfg_webname";

?>