<?php
$z[0]=Array("global","",118,151);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",164,197);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",241,274);
$z[2][4]['name']="cfg_webbiao";
$z[3]=Array("channel","\r\n        <li id=\"menu-item-60\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-60\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",750,1215);
$z[3][4]['type']="top";
$z[3][4]['row']="8";
$z[3][4]['currentstyle']="<li id='menu-item-40' class='menu-item menu-item-type-taxonomy menu-item-object-category current-post-ancestor current-menu-parent current-post-parent menu-item-40'><a href='~typelink~'>~typename~</a></li>";
$z[4]=Array("global","",1297,1331);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1419,1452);
$z[5][4]['name']="cfg_webname";

?>