<?php
$z[0]=Array("global","",283,308);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",390,417);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",420,446);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",646,676);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",4153,4179);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("myad","",4757,4778);
$z[5][4]['name']="1";
$z[6]=Array("myad","",5101,5124);
$z[6][4]['name']="tou";

?>